version: "3.6"
services:
  web:
    image: craftcms/nginx:7.4
    ports:
      - 8080:8080
    env_file: .env
    volumes:
      - ./:/app
    links:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: dev_craftcms
      MYSQL_USER: craft
      MYSQL_PASSWORD: password

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      - PMA_PORT=3306
      - PMA_HOST=mysql

  redis:
    image: redis
    ports:
      - 6379:6379
volumes:
  db_data:



















#version: '3.2'
#
#services:
#  db:
#    image: mysql:8.0
#    container_name: appsDB
#    restart: always
#    ports:
#      - '6603:3306'
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: db
#      MYSQL_USER: user
#      MYSQL_PASSWORD: password
#
#  phpmyadmin:
#    depends_on:
#      - db
#    image: phpmyadmin/phpmyadmin
#    container_name: phpmyadmin
#    restart: always
#    ports:
#      - '8080:80'
#    environment:
#      PMA_HOST: db

