version: "3.6"
services:
  web:
    #    image: craftcms/nginx:7.4
    image: craftcms/nginx:8.0
    ports:
      - 8080:8080
    env_file: .env
    volumes:
      - ./:/app
    links:
      - database
  database:
    container_name: mysql
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      - '3306'
    volumes:
      - ./datadir/dev:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      - database
    links:
      - database
    environment:
      PMA_HOST: database
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      DB_DATABASE: main
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  redis:
    image: redis
    ports:
      - 6379:6379
volumes:
  db_data:
